### ISSUE TITLE
Docker permissions issue

### ISSUE THREAD

**Issue by husamia** [AlgoLab/galig#11]
I am running into issues with group permission with docker.

>docker run -v "$PWD"/input:/data algolab/asgal:v1.1.1
Starting with UID:GID 0:0
groupadd: GID '0' already exists
useradd: group 'group' does not exist
error: failed switching to "user:group": unable to find user user: no matching entries in passwd file

**Comment by gdv** [comment]
May you please include some information on your system (e.g. which operating system/distribution), and on the contents of the `input` dir?

**Comment by husamia** [comment]
> May you please include some information on your system (e.g. which operating system/distribution), and on the contents of the `input` dir?

I am using Docker Desktop on Windows and input file has the sample data

**Comment by gdv** [comment]
Did you also run 
```
wget https://github.com/AlgoLab/galig/raw/master/example/input.tar.gz
tar xfz input.tar.gz
```
before running asgal? The error message you got usually happens when the `input` directory has not been created before.

**Comment by husamia** [comment]
yes, I did that.

**Comment by gdv** [comment]
May I ask you to provide the contents (and permissions) of the current directory and of the input directory?
Sorry, but I don't have a Windows machine to try to replicate your situation.

Take care

**Comment by husamia** [comment]
drwxrwxrwx 1 root root 4.0K Nov 25  2019 input

-rwxrwxrwx 1 root root  15K Jan 28  2018 annotation.gtf
-rwxrwxrwx 1 root root  23M Jan 28  2018 genome.fa
-rwxrwxrwx 1 root root 3.2M Jan 28  2018 sample_1.fa

**Comment by gdv** [comment]
Ok, then the problem is some sort of interaction with WSL. We expect that the input directory is owned by a regular user, not root.
I am going to update the docker image shortly to take into account this issue.
Thanks for the report.

**Comment by husamia** [comment]
Do you know how to pull the latest docker container with the fix?

**Comment by gdv** [comment]
If you delete the image with `docker rmi`, the next `docker run` should 
pull the updated container.
You can use `docker images` to see the list of your images.

Take care



Gianluca Della Vedova
https://gianluca.dellavedova.org

**Comment by husamia** [comment]
When I try to delete I get an error that another container is using it but I don't have that container
docker rmi d9fa1ddd9d21
Error response from daemon: conflict: unable to delete d9fa1ddd9d21 (must be forced) - image is being used by stopped container 4d03f790f96d
so I force delete it and when I pull it, it seems to not pulling the latest update for some reason..

**Comment by gdv** [comment]
I have uploaded a new image to docker hub.
May you please try `docker run -v "$PWD"/input:/data algolab/asgal:v1.1.2` ?

**Comment by husamia** [comment]
It's working now. I can't pass arguments using interactive mode i.e. -it with docker and bash.

**Comment by gdv** [comment]
The docker image has not been designed for interactive use.
What do you want to achieve? Maybe there is another way.

**Comment by husamia** [comment]
I want to do genome-wide analysis with my own data from RNA-Seq. I want to create new annotations from ensembl for GRCh38.

**Comment by gdv** [comment]
In this case, you should just copy your files into the input directory 
(or use a different directory in the `-v` option of `docker run`).

The filenames must be the same as those used in the sample dataset.

If you want to use different filenames, you need to compile asgal 
instead of using the docker image.

Take care.



Gianluca Della Vedova
https://gianluca.dellavedova.org
