### ISSUE TITLE
Another permissions question

### ISSUE THREAD

**Issue by raerose01** [AlgoLab/galig#15]
Hi, I'm attempting to run ASGAL via the Docker image and encounter an issue in the `salmon quant` step.

The error is
```
Traceback (most recent call last):
  File "/galig/asgal", line 585, in <module>
    main()
  File "/galig/asgal", line 576, in main
    runSalmon(args)
  File "/galig/asgal", line 210, in runSalmon
    command_check_return(salmon_quant_cmd, salmonBam, salmonQuantLog, shell=True, verbose=args.verbose)
  File "/galig/asgal", line 62, in command_check_return
    completed_process.check_returncode()
  File "/usr/lib/python3.8/subprocess.py", line 444, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '/galig/salmon/bin/salmon quant -p 2 -i /data/output/salmon/salmon_index -l A -1 /data/sample_1.fq -2 /data/sample_2.fq -o /data/output/salmon/salmon_out --no-version-check --validateMappings --writeMappings --writeUnmappedNames | samtools view -Sb - | samtools sort -' returned non-zero exit status 1.
```

And when I check the `log/salmon_quant.log` file it appears to be because of a permission denied error.

```
[E::hts_open_format] Failed to open file "./samtools.71.441.tmp.0000.bam" : Permission denied
samtools sort: failed to create temporary file "./samtools.71.441.tmp.0000.bam": Permission denied
```

Do you have any idea how to fix this?

Thanks!

Rachel

**Comment by gdv** [comment]
Dear Rachel,
can you share with us the log files, the input files you have used, and the complete command line that you have used?
We would also want to know the operating system you used and the docker version.
May you also check that you have enough free disk space?

**Comment by raerose01** [comment]
Hi,

Sure, I used this command, and definitely have enough free disk space:

`docker run -v "$PWD"/asgalgw_data:/data algolab/asgal:v1.1.3`

Logs: 

[salmon_index.log](https://github.com/AlgoLab/galig/files/6516808/salmon_index.log)
[salmon_quant.log](https://github.com/AlgoLab/galig/files/6516809/salmon_quant.log)

Operating system seems to be:

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

FASTQ files are somewhat large, but I'm using the following reference inputs:

http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf.gz
http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/GRCh37.p13.genome.fa.gz
http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.pc_transcripts.fa.gz

Thanks for the help,

Rachel

**Comment by ldenti** [comment]
Hi Rachel,
from what I can see (also from [samtools sort doc](http://www.htslib.org/doc/samtools-sort.html)), I would say that it's a problem of space. `samtools sort` stores a lot of temporary files in the current directory (it kinda splits the bam into multiple files before merging them into the final sorted bam). To avoid this, it's necessary to define the tmp directory to use (using `-T`).

The fastest and easiest solution is to `cd` to a directory where you know you have space (like the parent folder of the output folder you are using for running asgal) and then run asgal from there.

The other solution would be to update asgal code to allow user to define a temporary directory (but this'll take more time).

Let us know if this solves your issue.

Best.
Luca

**Comment by gdv** [comment]
Rachel,
can you please run the following command and report if it works?
```
docker run -v "$PWD"/asgalgw_data:/data algolab/asgal:v1.1.6
```

**Comment by raerose01** [comment]
Hi, yes, this seems to be working!

It's still running, but generating `samtools.71.8476.tmp.0000.bam` etc, in the `asgalgw_data/` directory.

Thanks!

Rachel

**Comment by gdv** [comment]
Yes, that was the intended effect.
Previously the location of the temporary files depended on the docker installation.

I am closing this bug, feel free to open another issue if any problem arises.
