### ISSUE TITLE
Novel intron retention events in genome-wide mode

### ISSUE THREAD

**Issue by raerose01** [AlgoLab/galig#17]
Hello, I had a more general question about running ASGAL in genome-wide mode. 

I have a dataset where I know there are 3 novel retained intron events. I was wondering if, after the pre-filtering step performed with by quasi-mapping with Salmon, the reads mapping to these novel retained introns would still be included in down-stream alternative splicing analysis. 

I'm asking because I have run ASGAL in genome-wide mode, but fail to detect any events. When I look at the output SAM file for a gene that should have a retained intron, there is no coverage (whereas when I look with a more typical spliced alignment to the reference genome tool, e.g. STAR, there is coverage). I have attached a screenshot of what I mean.
<img width="1059" alt="Screen Shot 2021-06-17 at 3 19 55 PM" src="https://user-images.githubusercontent.com/7635833/122415101-8854ff00-cf7f-11eb-84bc-83175a8230c6.png">

Could you let me know if I am mis-understanding something, or should be running the tool differently?

Thanks!

Rachel

**Comment by ldenti** [comment]
Hi Rachel,
unfortunately the current version of ASGAL cannot detect that kind of intron retention. Indeed, ASGAL aligns reads to the splicing graph (in other words to the known exons of a gene): in your case, there are a lot of reads mapping to an intron (as you can see from the coverage plot).

In the paper we said:
> We note that the current implementation of ASGAL is not able to detect the insertion of novel exons inside an intron and intron retention events caused by the union of two exons

Your case is exactly the second one we mentioned. Maybe it isn't clear enough: in case, sorry for that.

Best,
Luca

**Comment by raerose01** [comment]
Hi Luca,

OK, thanks for clarifying that.

Best,

Rachel
