### ISSUE TITLE
Building Docker image fails

### ISSUE THREAD

**Issue by KleinSamuel** [AlgoLab/galig#23]
Hello,

when building the Docker image I get the following error.

Steps to reproduce:
```
wget https://github.com/AlgoLab/galig/releases/tag/v1.1.7
tar xzvf galig-1.1.7.tar.gz
cd galig-1.1.7/docker/
docker build -t galig .
```
Part of the log:
```
[...]
STEP 10/16: RUN git clone --depth=1 --recursive https://github.com/AlgoLab/galig.git
Cloning into 'galig'...
--> 838ce15143da
STEP 11/16: RUN cd galig ; make prerequisites
make[1]: *** No rule to make target 'prerequisites'.  Stop.
make: *** [target.mk:17: /galig/obj] Error 2
Error: building at STEP "RUN cd galig ; make prerequisites": while running runtime: exit status 2
```

Do I need to use a specific version/tag for this to work?

**Comment by KleinSamuel** [comment]
Related to Issue https://github.com/AlgoLab/galig/issues/24

**Comment by ldenti** [comment]
I think this is now solved as well.

Just a bit more of info: we had to make some changes to compilation in order to publish [asgal in bioconda](https://anaconda.org/bioconda/asgal). This broke something. But anyway it is safe to use v1.1.7. In the meantime, we will try to fix the Dockerfile to use the latest version.

Thanks again!

**Comment by ldenti** [comment]
In any case, if you want to use docker and v1.1.8, you can use the [biocontainer](https://biocontainers.pro/tools/asgal) created by conda (thanks @yp for pointing this out):
```
docker pull quay.io/biocontainers/asgal:1.1.8--h43eeafb_1
docker run -it quay.io/biocontainers/asgal:1.1.8--h43eeafb_1 /bin/bash
/usr/local/bin/asgal --help
# this to list all binaries
ls /usr/local/bin/SpliceAwareAligner /usr/local/bin/asgal_*
```
