### ISSUE TITLE
Can not build

### ISSUE THREAD

**Issue by KleinSamuel** [AlgoLab/galig#24]
Hello,

I can not build the tool as described in your documentation (https://asgal.algolab.eu/documentation).

Steps to reproduce (inside Docker container using `ubuntu:24.10`):
```
sudo apt install -y build-essential cmake make wget git python3-pip samtools zlib1g-dev python3 python3-pip python3-setuptools python3-biopython python3-biopython-sql python3-pysam python3-pandas python3-setuptools python3-gffutils

git clone --recursive https://github.com/AlgoLab/galig.git
cd galig
git checkout v1.1.7
make prerequisites
```

The error I get:
```
[...]
-- Up-to-date: /opt/galig/lemon/compiled/include/lemon/concepts/path.h
-- Installing: /opt/galig/lemon/compiled/include/lemon/config.h
-- Installing: /opt/galig/lemon/compiled/lib/pkgconfig/lemon.pc
-- Installing: /opt/galig/lemon/compiled/bin/lgf-gen
-- Set non-toolchain portion of runtime path of "/opt/galig/lemon/compiled/bin/lgf-gen" to ""
-- Installing: /opt/galig/lemon/compiled/bin/dimacs-to-lgf
-- Set non-toolchain portion of runtime path of "/opt/galig/lemon/compiled/bin/dimacs-to-lgf" to ""
-- Installing: /opt/galig/lemon/compiled/bin/dimacs-solver
-- Set non-toolchain portion of runtime path of "/opt/galig/lemon/compiled/bin/dimacs-solver" to ""
-- Installing: /opt/galig/lemon/compiled/bin/lemon-0.x-to-1.x.sh
* SDSL-lite Library
/bin/sh: 4: ./install.sh: not found
make[1]: *** [/opt/galig/Makefile:107: /opt/galig/sdsl-lite/compiled] Error 127
make: *** [target.mk:17: /opt/galig/obj] Error 2
```

I am using the tag `v1.1.7` because with the `master` branch or tag `v1.1.8` the `make prerequisites` command fails with the following error:
```
make[1]: *** No rule to make target 'prerequisites'.  Stop.
make: *** [target.mk:17: /opt/galig/obj] Error 2
```

**Comment by KleinSamuel** [comment]
After a bit of investigation I found that the problem was that the `sdsl-lite` git submodule was not cloned properly.
When looking at the `master` branch, the connection to its repository is corrupted because the `.gitmodules` file is missing.

I was able to compile the project using the following command to directly clone a working version (tag `v1.1.7`) where the `.gitmodules` file was still present:
`git clone --depth 1 --branch v1.1.7 --recursive https://github.com/AlgoLab/galig.git`

**Comment by ldenti** [comment]
Hi,
you are right. That was the issue. I updated the Dockerfile (https://github.com/AlgoLab/galig/commit/698e0704583bb288169aefd4c9661206d6a44754). Thanks for troubleshooting it!
